name: Cypress Tesults

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress node command
        default: node runner.js

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Passo 1 sincronizando o npm
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run E2E tests
        run: ${{ github.event.inputs.spec }}
