name: Cypress Tests  

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5.0.0

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npx cypress run || chmod +x ./node_modules/.bin/cypress && npx cypress run

