name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-sequential:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: npm ci

      - name: Cypress run on Electron
        uses: cypress-io/github-action@v5.0.8
        with:
          ci-build-id: ${{ github.run_id }}
          browser: electron
          record: true
          parallel: false
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: fe84576b-e2e2-4da4-9ae4-16bf6fd63e6a
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v5.0.8
        with:
          ci-build-id: ${{ github.run_id }}
          browser: chrome
          record: true
          parallel: false
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: fe84576b-e2e2-4da4-9ae4-16bf6fd63e6a
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
