name: Cypress Test

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: npx cypress run

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
